# main.yml

name: CI Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python tests
      run: |
        pytest python-tests/

    - name: Validate Ansible playbooks
      run: |
        python ansible-tests/validate_playbook.py
        ansible-playbook ansible-tests/playbooks/sample-playbook.yml --check
